version: '3'
services:
  go_rest_api_boilerplate_mongodb:
    image: mongo
    container_name: go_rest_api_boilerplate_mongodb
    restart: always
    env_file:
      - ./app.env

    ports:
      - '6000:27017'
    volumes:
      - go_rest_api_boilerplate_mongodb:/data/db

  go_rest_api_boilerplate_redis:
    image: redis:alpine
    container_name: go_rest_api_boilerplate_redis
    ports:
      - '6379:6379'
    volumes:
      - go_rest_api_boilerplate_redis:/data
volumes:
  go_rest_api_boilerplate_mongodb:
  go_rest_api_boilerplate_redis:
